# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'win1803'

container: mcr.microsoft.com/windows/servercore:1803

steps:
- task: CmdLine@2  
  displayName: Prepare build environment 
  name: prepare
  timeoutInMinutes: 15
  inputs:
    script: |
      call prepare.bat

- task: CmdLine@2
  displayName: Build Calimero Project
  name: build_calimero
  timeoutInMinutes: 15
  inputs:
    script: |
      call build_calimero.bat
  
- task: PublishPipelineArtifact@1
  displayName: Publish Calimero Project
  name: publish_calimero
  inputs:
    targetPath: '$(Pipeline.Workspace)\out\calimero-core-2.5-SNAPSHOT.jar'
    artifact: 'calimero-core-2.5-SNAPSHOT.jar'
